(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['index'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"grid-100\">\n  <h1 class=\"name align-center\">Code Q&amp;A</h1>\n\n  <!-- question form -->\n  <form class=\"question-form\">\n    <div class=\"grid-parent\">\n      <div class=\"grid-100 circle--input--group\">\n        <input type=\"text\" placeholder=\"What's your question?\" id=\"question\">\n        <input class=\"button-primary\" type=\"submit\" value=\"Ask\">\n      </div>\n    </div>\n  </form><!-- /question form -->\n\n  <h2>Top Questions</h2>\n  <hr>\n\n  <!-- questions -->\n  <div class=\"grid-parent question\">\n    <div class=\"grid-10\">\n      <img class=\"avatar\" src=\"images/avatar.png\" alt=\"avatar\">\n    </div>\n    <div class=\"grid-90\">\n      <a href=\"question.html\">\n        <p>How to bind a custom function when the typeahead suggestion is selected with tab key?</p>\n        <small class=\"align-right block\">Asked <strong>June 23rd, 2015</strong></small>\n      </a>\n    </div>\n  </div> \n\n  <div class=\"grid-parent question\">\n    <div class=\"grid-10\">\n      <img class=\"avatar\" src=\"images/avatar.png\" alt=\"avatar\">\n    </div>\n    <div class=\"grid-90\">\n      <a class=\"question-wrap\" href=\"question.html\">\n        <p>How do I calculate the number of days in this year in Objective C?</p>\n        <small class=\"align-right block\">Asked <strong>May 1st, 2015</strong></small>\n      </a>\n    </div>\n  </div>       \n\n  <div class=\"grid-parent question\">\n    <div class=\"grid-10\">\n      <img class=\"avatar\" src=\"images/avatar.png\" alt=\"avatar\">\n    </div>\n    <div class=\"grid-90\">\n      <a class=\"question-wrap\" href=\"question.html\">\n        <p>How to find out which radio button the user selected in JavaScript?</p>\n        <small class=\"align-right block\">Asked <strong>October 18th, 2014</strong></small>\n      </a>\n    </div>\n  </div><!-- /questions -->\n\n</div>\n";
},"useData":true});
templates['question'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper;

  return "<div class=\"grid-100\">\n\n  <!-- main question -->\n  <h2 class=\"question-heading\">"
    + container.escapeExpression(((helper = (helper = helpers.word || (depth0 != null ? depth0.word : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : {},{"name":"word","hash":{},"data":data}) : helper)))
    + "How do I calculate the number of days in this year in Objective C?</h2>\n  <hr><!-- /main question -->\n\n  <!-- answers -->\n  <div class=\"grid-parent\">\n    <div class=\"grid-10\">\n      <div class=\"answer-voting\">\n        <span class=\"icon-chevron-up\"></span>\n        <strong class=\"vote-count\">3</strong></a>\n        <span class=\"icon-chevron-down\"></span>\n      </div>\n    </div>\n    <div class=\"grid-90\">\n      <p>What I do is first calculate the number of months in the year and then for each month calculate the number of days for that month.</p>\n      <div class=\"align-right\">\n        <small>Answered <strong>May 3rd, 2015 5:30pm</strong> |</small> \n        <small>Modified <strong>May 3rd, 2015 6:04pm</strong></small>\n      </div>\n    </div>\n  </div>\n  <hr>\n  <div class=\"grid-parent\">\n    <div class=\"grid-10\">\n      <div class=\"answer-voting\">\n        <span class=\"icon-chevron-up\"></span>\n        <strong class=\"vote-count\">10</strong></a>\n        <span class=\"icon-chevron-down\"></span>\n      </div>\n    </div>\n    <div class=\"grid-90\">\n      <p>Maybe you can use the <code>components:fromDate:toDate:options:</code> selector which is meant to (and I quote official Apple docs): Returns, as an NSDateComponents object using specified components, the difference between two supplied dates.</p>\n      <div class=\"align-right\">\n        <small>Answered <strong>May 3rd, 2015 5:30pm</strong> |</small> \n        <small>Modified <strong>May 3rd, 2015 6:04pm</strong></small>\n      </div>\n    </div>\n  </div><!-- /answers -->\n\n  <hr>\n  <h3>Add an Answer</h3>\n\n  <!-- answer form -->\n  <form>\n    <textarea class=\"full-width\" placeholder=\"Your answer...\" id=\"message\"></textarea>\n    <input class=\"button-primary\" type=\"submit\" value=\"Post answer\">\n  </form><!-- /answer form -->\n</div>\n";
},"useData":true});
})();